databases:
  - name: prizapp
    databaseName: mysite
    user: Sathya_Seelan

services:
  - type: web
    name: prizapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn prizapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prizapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4