# Generated by Django 3.2.16 on 2023-03-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('amazon_url', models.URLField()),
                ('amazon_price', models.FloatField()),
                ('flipkart_url', models.URLField()),
                ('flipkart_price', models.FloatField()),
            ],
        ),
    ]
